[package]
name = "nnos"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.9", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.6"
rtic = { version = "2.3.1", features = ["thumbv7-backend"] }
cortex-m-semihosting = "0.6.0"
stm32f4 = { version = "0.16.0", features = ["stm32f405", "rt"] }
