//! Everything wired together: bytes in, intent out. This is what an OS calls.

use alloc::vec::Vec;

use crate::decode::{Beams, Candidate, Greedy, MAX_GEN, beam};
use crate::format::LoadError;
use crate::intent;
use crate::model::{GenError, Model, Session};

pub struct Outcome {
    pub confidence: f32,
    pub min_token_prob: f32,
    /// generated bytes with the specials stripped. the embedder parses this into its
    /// own syscall type; the grammar is PRINT/READ/WRITE/CREATE/DELETE/LIST/TIME/
    /// REBOOT/NONE, all quoted args, paths always absolute
    pub output: Vec<u8>,
    /// full beam, empty in greedy mode. for a debug toggle
    pub candidates: Vec<Candidate>,
}

pub struct Shell {
    pub model: Model,
    pub session: Session,
    beams: Option<Beams>,
    max_tokens: usize,
}

impl Shell {
    /// `beam_width` of 1 means greedy, which is several times cheaper per command
    pub fn load(bytes: Vec<u8>, beam_width: usize) -> Result<Shell, LoadError> {
        let model = Model::load(bytes)?;
        let session = model.new_session();
        let beams = (beam_width > 1).then(|| Beams::new(&model, beam_width, MAX_GEN));
        Ok(Shell {
            model,
            session,
            beams,
            max_tokens: MAX_GEN,
        })
    }

    pub fn prompt_for(&self, listing: &[&str], line: &[u8]) -> Vec<u8> {
        intent::build_prompt(listing, line, self.model.cfg.ctx)
    }

    pub fn run(&mut self, listing: &[&str], line: &[u8]) -> Result<Outcome, GenError> {
        let prompt = self.prompt_for(listing, line);

        match &mut self.beams {
            Some(bs) => {
                let cands = beam(&self.model, &mut self.session, bs, &prompt)?;
                let best = cands.first().ok_or(GenError::NoRoomToGenerate)?;
                Ok(Outcome {
                    confidence: best.confidence,
                    min_token_prob: best.min_token_prob,
                    output: intent::output(&best.bytes).to_vec(),
                    candidates: cands,
                })
            }
            None => {
                let c = crate::decode::greedy(
                    &self.model,
                    &mut self.session,
                    &prompt,
                    self.max_tokens,
                )?;
                Ok(self.finish(c))
            }
        }
    }

    /// Stepwise greedy, for an executor that wants to yield between tokens. Ignores the
    /// beam width; beam search is a blocking call.
    pub fn start_greedy<'a>(
        &'a mut self,
        prompt: &[u8],
    ) -> Result<Greedy<'a, 'a>, GenError> {
        let Shell {
            model, session, ..
        } = self;
        Greedy::start(model, session, prompt, MAX_GEN)
    }

    pub fn finish(&self, c: Candidate) -> Outcome {
        Outcome {
            confidence: c.confidence,
            min_token_prob: c.min_token_prob,
            output: intent::output(&c.bytes).to_vec(),
            candidates: Vec::new(),
        }
    }
}
